/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author usuario
 */
public class Practica3 extends javax.swing.JFrame {

    /**
     * Creates new form Practica3
     */
    public Practica3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Botón 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Botón 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Random generadorNum = new Random();
        int numGenerado1 = generadorNum.nextInt(16)+1;
        int numGenerado2 = generadorNum.nextInt(16)+1;
        int numGenerado3 = generadorNum.nextInt(16)+1;
        int numGenerado4 = generadorNum.nextInt(16)+1;
        String secuenciaLetras = String.valueOf(numGenerado1 + "" + numGenerado2 + "" + numGenerado3 + "" + numGenerado4);
        String letra = "";

            switch (numGenerado1){
                case 1:
                    letra = "A";
                try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/A.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 2:
                    letra = "B";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/B.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 3:
                    letra = "C";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/C.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 4:
                    letra = "D";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/D.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 5:
                    letra = "E";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/E.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 6:
                    letra = "F";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/F.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 7:
                    letra = "G";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/G.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 8:
                    letra = "H";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/H.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 9:
                    letra = "I";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/I.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 10:
                    letra = "J";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/J.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 11:
                    letra = "K";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/K.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 12:
                    letra = "L";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/L.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 13:
                    letra = "M";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/M.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 14:
                    letra = "N";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/N.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 15:
                    letra = "O";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/O.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 16:
                    letra = "P";
                    try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/P.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
            }    
        
            
            switch (numGenerado2){
                case 1:
                    letra = "A";
                try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/A.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 2:
                    letra = "B";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/B.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 3:
                    letra = "C";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/C.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 4:
                    letra = "D";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/D.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 5:
                    letra = "E";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/E.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 6:
                    letra = "F";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/F.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 7:
                    letra = "G";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/G.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 8:
                    letra = "H";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/H.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 9:
                    letra = "I";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/I.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 10:
                    letra = "J";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/J.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 11:
                    letra = "K";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/K.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 12:
                    letra = "L";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/L.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 13:
                    letra = "M";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/M.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 14:
                    letra = "N";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/N.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 15:
                    letra = "O";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/O.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 16:
                    letra = "P";
                    try {
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/P.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
            }
            
            switch (numGenerado3){
                case 1:
                    letra = "A";
                try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/A.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 2:
                    letra = "B";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/B.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 3:
                    letra = "C";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/C.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 4:
                    letra = "D";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/D.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 5:
                    letra = "E";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/E.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 6:
                    letra = "F";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/F.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 7:
                    letra = "G";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/G.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 8:
                    letra = "H";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/H.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 9:
                    letra = "I";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/I.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 10:
                    letra = "J";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/J.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 11:
                    letra = "K";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/K.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 12:
                    letra = "L";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/L.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 13:
                    letra = "M";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/M.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 14:
                    letra = "N";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/N.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 15:
                    letra = "O";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/O.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 16:
                    letra = "P";
                    try {
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/P.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
            }
              
            
             switch (numGenerado4){
                case 1:
                    letra = "A";
                try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/A.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 2:
                    letra = "B";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/B.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 3:
                    letra = "C";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/C.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 4:
                    letra = "D";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/D.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 5:
                    letra = "E";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/E.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 6:
                    letra = "F";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/F.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 7:
                    letra = "G";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/G.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 8:
                    letra = "H";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/H.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 9:
                    letra = "I";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/I.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 10:
                    letra = "J";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/J.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 11:
                    letra = "K";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/K.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 12:
                    letra = "L";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/L.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 13:
                    letra = "M";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/M.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 14:
                    letra = "N";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/N.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 15:
                    letra = "O";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/O.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                case 16:
                    letra = "P";
                    try {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/P.png"))));
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
